/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.nhanViendao;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import pojo.nhanVienpojo;

/**
 *
 * @author ASUS
 */
public class quanLiTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form quanLiTaiKhoan
     */
    ArrayList<nhanVienpojo> dsNV = nhanViendao.layDSNV(); 
    DefaultTableModel dtm = new DefaultTableModel();
    public quanLiTaiKhoan() {
        initComponents();
        String []tieude ={"Mã nhân viên","Tên nhân viên","SDT_Nhân viên","Ngày sinh","Địa chỉ","Giới tính","Chức vụ"};
        dtm.setColumnIdentifiers(tieude);
        hienThiNhanVien();
    }
   private void hienThiNhanVien() {
        dtm.setRowCount(0);
       for (nhanVienpojo s:dsNV)
       {
           Vector<Object> v = new Vector<Object>();
           v.add(s.getMaNV());
           v.add(s.getTenNV());
           v.add(s.getSDT_NV());
           v.add(s.getNgaySinh());
           v.add(s.getDiaChi());
           v.add(s.getGioiTinh());
           v.add(s.getChucVu());
           dtm.addRow(v);
       }tbl_nv.setModel(dtm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        manv = new javax.swing.JTextField();
        tenv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nv = new javax.swing.JTable();
        sua = new javax.swing.JButton();
        as = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        luu = new javax.swing.JButton();
        timKiem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cl_bt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diachi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ngayS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        matkhau = new javax.swing.JTextField();
        gt = new javax.swing.JComboBox();
        chucvu = new javax.swing.JComboBox();

        sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdtActionPerformed(evt);
            }
        });

        jLabel11.setText("SDT_Nhân viên");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin nhân viên");

        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        tbl_nv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nv);

        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        sua.setText("Sữa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        as.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        as.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        as.setText("Tìm kiếm");

        jLabel2.setText("Mã nhân viên");

        jLabel3.setText("Tên nhân viên");

        luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        luu.setText("Lưu");
        luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuActionPerformed(evt);
            }
        });

        timKiem.setText("Tìm");
        timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemActionPerformed(evt);
            }
        });

        jLabel5.setText("Giới tính");

        cl_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/broom.png"))); // NOI18N
        cl_bt.setText("Clean");
        cl_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_btActionPerformed(evt);
            }
        });

        jLabel6.setText("Chức vụ");

        jLabel4.setText("Địa chỉ");

        diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diachiActionPerformed(evt);
            }
        });

        jLabel7.setText("Ngày sinh");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*Chú ý: tài khoản đăng nhập chính là mã nhân viên");

        jLabel9.setText("Mật khẩu");

        gt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Chọn giới tính---", "Nam", "Nữ" }));

        chucvu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Chọn chúc vụ---", "Quản lí", "Nhân viên" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(as, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timten, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timKiem))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(matkhau)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(manv, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tenv, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ngayS, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                            .addComponent(diachi)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(gt, 0, 286, Short.MAX_VALUE)
                                                .addComponent(chucvu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(luu)
                                                .addGap(18, 18, 18)
                                                .addComponent(sua)
                                                .addGap(18, 18, 18)
                                                .addComponent(xoa)
                                                .addGap(18, 18, 18)
                                                .addComponent(cl_bt)))))
                                .addContainerGap(29, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as)
                    .addComponent(timten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tenv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ngayS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(luu)
                            .addComponent(sua)
                            .addComponent(xoa)
                            .addComponent(cl_bt))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // button thêm
        manv.setText("");
        tenv.setText("");
        gt.setSelectedIndex(0);
        ngayS.setText("");
        chucvu.setSelectedIndex(0);
        sdt.setText("");
        matkhau.setText("");
        diachi.setText("");
        timten.setText("");
        manv.requestFocus();
        tbl_nv.setRowSorter(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nvMouseClicked
        // TODO add your handling code here:
        int row = this.tbl_nv.getSelectedRow();
        this.manv.setText((String)(tbl_nv.getValueAt(row, 0)));
        this.tenv.setText((String)(tbl_nv.getValueAt(row, 1)));
//        this.sdt.setText(Integer.toString((Integer)tbl_nv.getValueAt(row, 2)));
        this.sdt.setText((String)(tbl_nv.getValueAt(row, 2)));
        this.ngayS.setText((String)(tbl_nv.getValueAt(row, 3)));
        this.diachi.setText((String)(tbl_nv.getValueAt(row, 4)));
        this.gt.setSelectedItem((String)(tbl_nv.getValueAt(row, 5)));
        this.chucvu.setSelectedItem((String)(tbl_nv.getValueAt(row, 6)));
        matkhau.setText("");
        

    }//GEN-LAST:event_tbl_nvMouseClicked

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        if(tbl_nv.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = manv.getText().trim();
                String hoten = tenv.getText().trim();
                String sdtnv = sdt.getText().trim();
                String nsinh = ngayS.getText().trim();
                String diachinv = diachi.getText().trim();
                String gioitinh = gt.getSelectedItem().toString();
//                String taikhoan = manv.getText().trim();
                String matkhaunv = matkhau.getText().trim();
                String chucvuNV = chucvu.getSelectedItem().toString();
                
                String sql = "set dateformat dmy\n" +
                "update nhanVien set TenNV = N'"+hoten+"', NgaySinh = '"+nsinh+"', GioiTinh = N'"+gioitinh+"', \n" +
                "DiaChi = N'"+diachinv+"', SDT_NV = '"+sdtnv+"',  \n" +
                "MatKhau = '"+matkhaunv+"', ChucVu = '"+chucvuNV+"' where MaNV = '"+ma+"'";
                
                nhanViendao.ThemXoaSua(sql);
                dsNV = nhanViendao.layDSNV();
                hienThiNhanVien();
                JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
            }
        }else{
            if(tbl_nv.getRowCount()==0) 
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
        }
    }//GEN-LAST:event_suaActionPerformed

    private void timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemActionPerformed
        // TODO add your handling code here:
        String ten = timten.getText().trim();
        DefaultTableModel dtm = (DefaultTableModel)tbl_nv.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        tbl_nv.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ten));
        
    }//GEN-LAST:event_timKiemActionPerformed

    private void cl_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_btActionPerformed
        // TODO add your handling code here:
        manv.setText("");
        tenv.setText("");       
        gt.setSelectedIndex(0);
        chucvu.setSelectedIndex(0);     
        sdt.setText("");
        diachi.setText("");
        matkhau.setText("");
        ngayS.setText("");
        timten.setText("");
        manv.requestFocus();
        tbl_nv.setRowSorter(null);
    }//GEN-LAST:event_cl_btActionPerformed

    private void diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diachiActionPerformed

    private void luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String ma = manv.getText().trim();
            String hoten = tenv.getText().trim();
            String sdtnv = sdt.getText().trim();
            String nsinh = ngayS.getText().trim();
            String diachinv = diachi.getText().trim();
            String gioitinh = gt.getSelectedItem().toString();
            String taikhoan = manv.getText().trim();
            String matkhaunv = matkhau.getText().trim();
            String chucvuNV = chucvu.getSelectedItem().toString();
            
            
            String sql="set dateformat dmy\n" + "insert into nhanVien\n" +
            "values ('"+ma+"', N'"+hoten+"', '"+sdtnv+"', '"+nsinh+"', N'"+diachinv+"', N'"+gioitinh+"','"+taikhoan+"', '"+matkhaunv+"','"+chucvuNV+"')";
            int kq=nhanViendao.ThemXoaSua(sql);
            if(kq!=-1)
            {
                dsNV = nhanViendao.layDSNV();
                hienThiNhanVien();
                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã NV này đã tồn tại, không thể thêm", "Thông báo", 2);
        }
    }//GEN-LAST:event_luuActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        if(tbl_nv.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = manv.getText().trim();
                
                String sql = "delete from NhanVien where MaNV = '"+ma+"'";
                if(nhanViendao.ThemXoaSua(sql)!=-1)
                {
                    dsNV = nhanViendao.layDSNV();
                    hienThiNhanVien();
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    
            }
        }else{
            if(tbl_nv.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel as;
    private javax.swing.JComboBox chucvu;
    private javax.swing.JButton cl_bt;
    private javax.swing.JTextField diachi;
    private javax.swing.JComboBox gt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luu;
    private javax.swing.JTextField manv;
    private javax.swing.JTextField matkhau;
    private javax.swing.JTextField ngayS;
    private javax.swing.JTextField sdt;
    private javax.swing.JButton sua;
    private javax.swing.JTable tbl_nv;
    private javax.swing.JTextField tenv;
    private javax.swing.JButton timKiem;
    private javax.swing.JTextField timten;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables

    
}
