/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ctdonHang;
import dao.donHangdao;
import dao.khachHangdao;
import dao.sachdao;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import pojo.ctdonHangpojo;
import pojo.donHangpojo;
import pojo.khachHangpojo;
import pojo.sachpojo;

/**
 *
 * @author ASUS
 */
public class quanLiDonHang extends javax.swing.JPanel {

    /**
     * Creates new form quanLiDonHang
     */
    ArrayList<sachpojo> dsS_donHang = sachdao.layDanhSachSach_donHang();
    ArrayList<khachHangpojo>dsKH=khachHangdao.layDSkhachHang();
    ArrayList<donHangpojo>dsHD=donHangdao.layDSDONHANG();
    ArrayList<ctdonHangpojo>dsct=ctdonHang.layDSCT();
    DefaultTableModel dtm_DH = new DefaultTableModel();
    DefaultTableModel dtm_SACH = new DefaultTableModel();
    DefaultTableModel dtm_KH = new DefaultTableModel();
    DefaultTableModel dtm_CT = new DefaultTableModel();
    
    public quanLiDonHang() {
        initComponents();
        String []tieude ={"Mã sách","Tên sách","Số lượng","Giá"};
        dtm_SACH.setColumnIdentifiers(tieude);  
        String []tieude_KHACHHANG ={"Mã","Tên khách hàng","Số điện thoại"};
        dtm_KH.setColumnIdentifiers(tieude_KHACHHANG);
        hienthiSACH();
        hientthiKHACHHANG();
        String []tieude_DH ={"Mã Đơn Hàng","Mã Nhân Viên","Mã Khách Hàng","Mã sách","Tên Khách Hàng","Ngày Đặt","Số Lượng","Thành tiền"};
        dtm_DH.setColumnIdentifiers(tieude_DH);
        hienThi_DH();
        String []tieude_CT ={"Mã","Mã khách hàng","Ngày mua","Tổng tiền"};
        dtm_CT.setColumnIdentifiers(tieude_CT);
        hienthiCT();
    }
    private void hienthiSACH() {
        dtm_SACH.setRowCount(0);
       for (sachpojo s:dsS_donHang)
       {
           Vector<Object> v = new Vector<Object>();
           v.add(s.getMaSach());
           v.add(s.getTenSach());
           v.add(s.getSoLuong());
           v.add(s.getGia());
           
           dtm_SACH.addRow(v);
       }tbl_sach_donHang.setModel(dtm_SACH);
    }
    private void hientthiKHACHHANG() {
        dtm_KH.setRowCount(0);
        for(khachHangpojo kh:dsKH)
        {
            Vector<Object> v_kh= new Vector<Object>();
            v_kh.add(kh.getMaKH());
            v_kh.add(kh.getTenKH());
            v_kh.add(kh.getSDT_KH());
            dtm_KH.addRow(v_kh);            
        }tbl_khachHang.setModel(dtm_KH);
    }
    private void hienThi_DH() {
        dtm_DH.setRowCount(0);
       for (donHangpojo hd:dsHD)
       {
           Vector<Object> v = new Vector<Object>();
           v.add(hd.getMaHD());
           v.add(hd.getMaNV());
           v.add(hd.getMaKH());
           v.add(hd.getMaSach());
           v.add(hd.getTenKH());
           v.add(hd.getNgayMua());
           v.add(hd.getSoLuong());
           v.add(hd.getThanhTien());
           dtm_DH.addRow(v);
       }
       tbl_donHAng.setModel(dtm_DH);
    }
     private void hienthiCT() {
        dtm_CT.setRowCount(0);
        for(ctdonHangpojo ct:dsct)
        {
            Vector<Object> v_ct= new Vector<Object>();
            v_ct.add(ct.getMaCT());
            v_ct.add(ct.getMaKH());
            v_ct.add(ct.getNgayMua());
            v_ct.add(ct.getTongTT());
            dtm_CT.addRow(v_ct); 
        }tbl_ct.setModel(dtm_CT);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sach_donHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        timten = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        themKH = new javax.swing.JButton();
        luuKH = new javax.swing.JButton();
        suuKH = new javax.swing.JButton();
        txttenKhach = new javax.swing.JTextField();
        sdt_khach = new javax.swing.JTextField();
        xoaKH = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtmaKH = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtsach = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        themdonhang = new javax.swing.JButton();
        xoadh = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtmaDH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtmaS = new javax.swing.JTextField();
        luuuuuu = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_donHAng = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_ct = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thông tin sách");

        tbl_sach_donHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sach_donHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sach_donHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sach_donHang);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        jLabel1.setText("Tìm kiếm");

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Bảng thông tin sách");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(timten, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile-user.png"))); // NOI18N
        jLabel8.setText("Thông tin khách hàng");

        jLabel9.setText("Tên khách hàng");

        jLabel10.setText("Số điện thoại");

        themKH.setText("Thêm");
        themKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themKHActionPerformed(evt);
            }
        });

        luuKH.setText("Lưu");
        luuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuKHActionPerformed(evt);
            }
        });

        suuKH.setText("Sữa");
        suuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suuKHActionPerformed(evt);
            }
        });

        sdt_khach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdt_khachActionPerformed(evt);
            }
        });

        xoaKH.setText("Xóa");
        xoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaKHActionPerformed(evt);
            }
        });

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_khachHang);

        jLabel11.setText("Mã khách hàng");

        txtmaKH.setRequestFocusEnabled(false);

        jLabel19.setText("Bảng thông tin khách hàng");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sdt_khach, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(themKH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(luuKH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suuKH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xoaKH))
                            .addComponent(jLabel19))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txttenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sdt_khach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themKH)
                    .addComponent(luuKH)
                    .addComponent(suuKH)
                    .addComponent(xoaKH))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setText("Tên sách");

        jLabel5.setText("Giá");

        jLabel6.setText("Số lượng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Thông tin đơn hàng");

        themdonhang.setText("Thêm đơn hàng");
        themdonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themdonhangActionPerformed(evt);
            }
        });

        xoadh.setText("Xóa đơn hàng");
        xoadh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoadhActionPerformed(evt);
            }
        });

        jLabel13.setText("Mã đơn hàng");

        txtmaDH.setRequestFocusEnabled(false);

        jLabel14.setText("Mã nhân viên");

        jLabel15.setText("Ngày mua");

        jLabel18.setText("Mã sách");

        txtmaS.setRequestFocusEnabled(false);

        luuuuuu.setText("Lưu hóa đơn");
        luuuuuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuuuuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsach, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtSL)
                            .addComponent(txtgia)
                            .addComponent(txtmaS))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmaDH)
                                    .addComponent(txtmaNV)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(themdonhang)
                                .addGap(18, 18, 18)
                                .addComponent(xoadh)
                                .addGap(18, 18, 18)
                                .addComponent(luuuuuu)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtmaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtmaDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoadh)
                    .addComponent(themdonhang)
                    .addComponent(luuuuuu))
                .addGap(24, 24, 24))
        );

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        tbl_donHAng.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_donHAng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_donHAngMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_donHAng);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_ct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_ct);

        jLabel16.setText("Bảng đơn hàng");

        jLabel17.setText("Bảng chi tiết đơn hàng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane2.addTab("Đơn hàng", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //tim kiếm
        String ten = timten.getText().trim();
        DefaultTableModel dtm = (DefaultTableModel)tbl_sach_donHang.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        tbl_sach_donHang.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ten));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sdt_khachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdt_khachActionPerformed

    }//GEN-LAST:event_sdt_khachActionPerformed

    private void themKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themKHActionPerformed
        // TODO add your handling code here:
        txttenKhach.setText("");
        txtmaKH.setText("");
        sdt_khach.setText("");
        timten.setText("");
        txttenKhach.requestFocus();
        tbl_khachHang.setRowSorter(null);
    }//GEN-LAST:event_themKHActionPerformed

    private void luuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuKHActionPerformed
        // TODO add your handling code here:
            String tenKH = txttenKhach.getText().trim();
            String sdt_KH = sdt_khach.getText().trim();
            String sql="insert into khachHang\n" +
            "values (N'"+tenKH+"', '"+sdt_KH+"')";
            int kq=khachHangdao.ThemXoaSuaKH(sql);
            if(kq!=-1)
            {
                dsKH = khachHangdao.layDSkhachHang();
                hientthiKHACHHANG();
                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã này đã tồn tại, không thể thêm", "Thông báo", 2);
        
    }//GEN-LAST:event_luuKHActionPerformed

    private void tbl_khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachHangMouseClicked
        // TODO add your handling code here:
        int row = this.tbl_khachHang.getSelectedRow();
        this.txtmaKH.setText(Integer.toString((Integer)tbl_khachHang.getValueAt(row, 0)));
        this.txttenKhach.setText((String)(tbl_khachHang.getValueAt(row, 1)));
        this.sdt_khach.setText((String)(tbl_khachHang.getValueAt(row, 2)));
    }//GEN-LAST:event_tbl_khachHangMouseClicked

    private void tbl_sach_donHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sach_donHangMouseClicked
        // TODO add your handling code here:
        int row = this.tbl_sach_donHang.getSelectedRow();
        this.txtmaS.setText((String)(tbl_sach_donHang.getValueAt(row, 0)));
        this.txtsach.setText((String)(tbl_sach_donHang.getValueAt(row, 1)));
        this.txtgia.setText(Integer.toString((Integer)tbl_sach_donHang.getValueAt(row, 3)));
    }//GEN-LAST:event_tbl_sach_donHangMouseClicked

    private void suuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suuKHActionPerformed
        // TODO add your handling code here:
        if(tbl_khachHang.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String tenKH = txttenKhach.getText().trim();
                String sdtKH = sdt_khach.getText().trim();
                String sql = "update khachHang set TenKH = N'"+tenKH+"', sdt_KH = '"+sdtKH+"'" ;
                khachHangdao.ThemXoaSuaKH(sql);
                dsKH = khachHangdao.layDSkhachHang();
                hientthiKHACHHANG();
                JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
            }
        }else{
            if(tbl_khachHang.getRowCount()==0) 
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
        }
    }//GEN-LAST:event_suuKHActionPerformed

    private void xoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaKHActionPerformed
        // TODO add your handling code here:
        if(tbl_khachHang.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String maKH = txtmaKH.getText().trim();
                String sql = "delete from khachHang where maKH = '"+maKH+"'";
                if(khachHangdao.ThemXoaSuaKH(sql)!=-1)
                {
                    dsKH = khachHangdao.layDSkhachHang();
                    hientthiKHACHHANG();
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);     
            }
        }else{
            if(tbl_khachHang.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_xoaKHActionPerformed

    private void themdonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themdonhangActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
           String ma_NV = txtmaNV.getText().trim();
           String maSS=txtmaS.getText().trim();
            String maKH = txtmaKH.getText().trim();
            String tenKH = txttenKhach.getText().trim();
            String ngay = date.getText().trim();
            int soL = 0;
            soL=Integer.parseInt(txtSL.getText());
            int gia= 0;
            gia=Integer.parseInt(txtgia.getText());
            int tt = soL*gia;
            String sql_DH="insert into donHang\n" +
            "values('"+ma_NV+"','"+maKH+"','"+maSS+"','"+tenKH+"','"+ngay+"','"+soL+"','"+tt+"')";
            int kq=donHangdao.ThemXoaSua_DH(sql_DH);
            if(kq!=-1)
            {
                dsHD = donHangdao.layDSDONHANG();
                hienThi_DH();
                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã này đã tồn tại, không thể thêm", "Thông báo", 2);
        }
    }//GEN-LAST:event_themdonhangActionPerformed

    private void xoadhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoadhActionPerformed
        // TODO add your handling code here:
        if(tbl_donHAng.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String madh = txtmaDH.getText().trim();
                
                String sql = "delete from donHang where maDH = '"+madh+"'";
                if(sachdao.ThemXoaSua(sql)!=-1)
                {
                    dsHD = donHangdao.layDSDONHANG();
                    hienThi_DH();
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    
            }
        }else{
            if(tbl_donHAng.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_xoadhActionPerformed

    private void tbl_donHAngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_donHAngMouseClicked
        // TODO add your handling code here:
        int row = tbl_donHAng.getSelectedRow();
        txtmaDH.setText(String.valueOf(tbl_donHAng.getValueAt(row, 0)));
        txtmaNV.setText(String.valueOf(tbl_donHAng.getValueAt(row, 1)));
        txtmaKH.setText(String.valueOf(tbl_donHAng.getValueAt(row, 2)));
        txtmaS.setText(String.valueOf(tbl_donHAng.getValueAt(row, 3)));
        txttenKhach.setText(String.valueOf(tbl_donHAng.getValueAt(row, 4)));
        date.setText(String.valueOf(tbl_donHAng.getValueAt(row, 5)));
        txtSL.setText(String.valueOf(tbl_donHAng.getValueAt(row, 6))); 
    }//GEN-LAST:event_tbl_donHAngMouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void luuuuuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuuuuuActionPerformed
        // TODO add your handling code here:
            String makh = txtmaKH.getText().trim();
            String ngaymua = date.getText().trim();
            int gia=0;
            for(int i=0;i<tbl_donHAng.getRowCount();i++)
            {
                gia+=Integer.parseInt(tbl_donHAng.getValueAt(i, 7).toString());
            }
            String sql="insert into ct_DonHang\n" +
            "values ('"+makh+"', '"+ngaymua+"','"+gia+"')";
            int kq=ctdonHang.ThemXoaSua_CT(sql);
            if(kq!=-1)
            {
                dsct = ctdonHang.layDSCT();
                hienthiCT();
                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã này đã tồn tại, không thể thêm", "Thông báo", 2);
    }//GEN-LAST:event_luuuuuuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton luuKH;
    private javax.swing.JButton luuuuuu;
    private javax.swing.JTextField sdt_khach;
    private javax.swing.JButton suuKH;
    private javax.swing.JTable tbl_ct;
    private javax.swing.JTable tbl_donHAng;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTable tbl_sach_donHang;
    private javax.swing.JButton themKH;
    private javax.swing.JButton themdonhang;
    private javax.swing.JTextField timten;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtmaDH;
    private javax.swing.JTextField txtmaKH;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField txtmaS;
    private javax.swing.JTextField txtsach;
    private javax.swing.JTextField txttenKhach;
    private javax.swing.JButton xoaKH;
    private javax.swing.JButton xoadh;
    // End of variables declaration//GEN-END:variables
}
