/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.loaiSachdao;
import dao.sachdao;
import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.omg.CORBA.OBJECT_NOT_EXIST;
import pojo.loaiSachpojo;
import pojo.sachpojo;

/**
 *
 * @author ASUS
 */
public class quanLiSanPham extends javax.swing.JPanel {

    /**
     * Creates new form quanLiSanPham
     */
    Vector tblDataSP = new Vector();
    Vector tblTitleSP = new Vector();
    Vector tblDataLSP = new Vector();
    Vector tblTitleLSP = new Vector();
    ArrayList<sachpojo> dsS = sachdao.layDanhSachS(); 
    ArrayList<loaiSachpojo> loaiS=loaiSachdao.layLoaiSach();
    DefaultTableModel dtm = new DefaultTableModel();
    public quanLiSanPham() {
        initComponents();
        bangLS();
        bangSP();
        laydulieuLS(loaiS);
        laydulieuS(dsS);
        setcbo_loaisp();
      
    }
    private void bangLS() {
        tblTitleLSP.add("Mã loại sách"); tblTitleLSP.add("Tên loại sách"); 
    }
    private void bangSP() {
        tblTitleSP.add("Mã sách");
        tblTitleSP.add("Tên sách");
        tblTitleSP.add("Loại");
        tblTitleSP.add("Tác giả");
        tblTitleSP.add("Nhà xuất bản");
        tblTitleSP.add("Nhà cung cấp");
        tblTitleSP.add("Loại bìa");
        tblTitleSP.add("Số lượng");
        tblTitleSP.add("Năm xuất bản");
        tblTitleSP.add("Giá");
        tblTitleSP.add("Hình ảnh");
    }

    private void laydulieuLS(ArrayList<loaiSachpojo> loaiS) {
        tblDataLSP.removeAllElements();
        for(loaiSachpojo ls : loaiS){
            Vector v = new Vector();
            v.add(ls.getMaLoai()); 
            v.add(ls.getTenLoai());
            tblDataLSP.add(v);
        }
        tbl_loai.setModel(new DefaultTableModel(tblDataLSP, tblTitleLSP));
    }

    private void laydulieuS(ArrayList<sachpojo> dsS) {
        tblDataSP.removeAllElements();
        for (sachpojo s:dsS)
       {
           Vector<Object> v = new Vector<Object>();
           v.add(s.getMaSach());
           v.add(s.getTenSach());
           v.add(s.getMaLoai());
           v.add(s.getTacGia());
           v.add(s.getNhaXuatBan());
           v.add(s.getNhaCungCap());
           v.add(s.getLoaiBia());
           v.add(s.getSoLuong());
           v.add(s.getNamXB());
           v.add(s.getGia());
           v.add(s.getHinhAnh());
           tblDataSP.add(v);
       }
        tbl.setModel(new DefaultTableModel(tblDataSP, tblTitleSP));
    }

    private void setcbo_loaisp() {
       for(loaiSachpojo i : loaiS){
            loai.addItem(i.getTenLoai());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        sl = new javax.swing.JTextField();
        namxb = new javax.swing.JTextField();
        gia = new javax.swing.JTextField();
        bia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        anh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ma = new javax.swing.JTextField();
        tenSach = new javax.swing.JTextField();
        tacgia = new javax.swing.JTextField();
        nxb = new javax.swing.JTextField();
        ncc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        xoa = new javax.swing.JButton();
        f = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        sua = new javax.swing.JButton();
        as = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        luu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        timKiem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cl_bt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        loai = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        d = new javax.swing.JScrollPane();
        tbl_loai = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        kimloai = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        maloai = new javax.swing.JTextField();
        tenloai = new javax.swing.JTextField();
        them = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        xoaloai = new javax.swing.JButton();
        sualoai = new javax.swing.JButton();
        cl_loai = new javax.swing.JButton();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaActionPerformed(evt);
            }
        });

        jLabel7.setText("Nhà cung cấp");

        jLabel13.setText("Hình ảnh");

        jLabel9.setText("Số lượng");

        jLabel10.setText("Năm xuất bản");

        jLabel11.setText("Giá");

        ma.setRequestFocusEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin sách");

        xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        f.setViewportView(tbl);

        sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        sua.setText("Sữa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        as.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        as.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        as.setText("Tìm kiếm");

        jLabel2.setText("Mã sách");

        jLabel3.setText("Tên sách");

        luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        luu.setText("Lưu");
        luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuActionPerformed(evt);
            }
        });

        jLabel4.setText("Loại sách");

        timKiem.setText("Tìm");
        timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemActionPerformed(evt);
            }
        });

        jLabel5.setText("Tác giả");

        cl_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/broom.png"))); // NOI18N
        cl_bt.setText("Clean");
        cl_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_btActionPerformed(evt);
            }
        });

        jLabel6.setText("Nhà xuất bản");

        loai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Loại sách---" }));

        jLabel12.setText("Loại bìa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(as, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timten, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timKiem)))
                .addContainerGap(1270, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(namxb, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(gia, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bia, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tacgia, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nxb, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loai, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(luu)
                        .addGap(18, 18, 18)
                        .addComponent(sua)
                        .addGap(18, 18, 18)
                        .addComponent(xoa)
                        .addGap(18, 18, 18)
                        .addComponent(cl_bt)
                        .addGap(178, 178, 178))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(as)
                    .addComponent(timten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(bia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(namxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(luu)
                            .addComponent(sua)
                            .addComponent(xoa)
                            .addComponent(cl_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104))))
        );

        jTabbedPane1.addTab("Sách", jPanel2);

        tbl_loai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_loai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_loaiMouseClicked(evt);
            }
        });
        d.setViewportView(tbl_loai);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Thông tin loại sách");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        jLabel14.setText("Tìm kiếm");

        jButton2.setText("Tìm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Mã loại");

        jLabel16.setText("Tên loại");

        maloai.setRequestFocusEnabled(false);

        them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        jButton5.setText("Lưu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        xoaloai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.png"))); // NOI18N
        xoaloai.setText("Xóa");
        xoaloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaloaiActionPerformed(evt);
            }
        });

        sualoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        sualoai.setText("Sữa");
        sualoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sualoaiActionPerformed(evt);
            }
        });

        cl_loai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/broom.png"))); // NOI18N
        cl_loai.setText("Clean");
        cl_loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_loaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maloai)
                                    .addComponent(tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(them)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(xoaloai)
                                .addGap(18, 18, 18)
                                .addComponent(sualoai)
                                .addGap(18, 18, 18)
                                .addComponent(cl_loai))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kimloai, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(kimloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(maloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(them)
                            .addComponent(jButton5)
                            .addComponent(xoaloai)
                            .addComponent(sualoai)
                            .addComponent(cl_loai))
                        .addGap(157, 157, 157))))
        );

        jTabbedPane1.addTab("Loại sách", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // button thêm
        ma.setText("");
        tenSach.setText("");
        loai.setSelectedIndex(0);
        tacgia.setText("");
        nxb.setText("");
        ncc.setText("");
        bia.setText("");
        sl.setText("");
        this.loai.setEnabled(true);
        namxb.setText("");
        gia.setText("");
        timten.setText("");
        anh.setText("");
        tenSach.requestFocus();
        tbl.setRowSorter(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int row = this.tbl.getSelectedRow();
        this.ma.setText((String)(tbl.getValueAt(row, 0)));
        this.ma.setEditable(false);
        this.loai.setEnabled(false);
        this.tenSach.setText((String)(tbl.getValueAt(row, 1)));
        this.loai.setSelectedItem((String)(tbl.getValueAt(row, 2)));
        this.tacgia.setText((String)(tbl.getValueAt(row, 3)));
        this.nxb.setText((String)(tbl.getValueAt(row, 4)));
        this.ncc.setText((String)(tbl.getValueAt(row, 5)));
        this.bia.setText((String)(tbl.getValueAt(row, 6)));
        this.sl.setText(Integer.toString((Integer)tbl.getValueAt(row, 7)));
        this.namxb.setText((String)(tbl.getValueAt(row, 8)));
        this.gia.setText(Integer.toString((Integer)tbl.getValueAt(row, 9)));
        this.anh.setText((String)(tbl.getValueAt(row, 10)));
        
//        String path=("C:\\Users\\ASUS\\OneDrive\\Tài liệu\\Java\\shopBook\\src\\hinh\\");
//        anh.getText().equals(path+"");  
//        ImageIcon imgicon = new ImageIcon(new ImageIcon(anh.getText()).getImage().getScaledInstance(180, 250, Image.SCALE_SMOOTH));
//        lb_anh.setIcon(imgicon);
        
    }//GEN-LAST:event_tblMouseClicked

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        if(tbl.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String maS = ma.getText().trim();
                String tenS = tenSach.getText().trim();
                String loaiS = loai.getSelectedItem().toString();
                String tacG = tacgia.getText().trim();
                String nhaxb = nxb.getText().trim();
                String nhacc = ncc.getText().trim();
                String loaiB = bia.getText().trim();
                String hA = anh.getText().trim();
                String soL = sl.getText().trim();
                String namXb= namxb.getText().trim();
                String G=gia.getText().trim();
                this.loai.setEditable(false);
                String sql ="update Sach set tenSach = N'"+tenS+"',  \n" + 
//                "maLoai = (select left("+loaiS.trim()+",2)from loaiSach where maLoai=convert(int,LEFT(+"+loaiS.trim()+",2))),"+
                "tacGia = N'"+tacG+"',nhaXuatBan=N'"+nhaxb+"',nhaCungCap=N'"+nhacc+"',loaiBia=N'"+loaiB+"',hinhAnh='"+hA+"',soLuong='"+soL+"',namXB='"+namXb+"',Gia='"+G+"'\n" +
                "where maSach='"+maS+"'";
                
                sachdao.ThemXoaSua(sql);
                dsS = sachdao.layDanhSachS();
                laydulieuS(dsS);
                JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
            }
        }else{
            if(tbl.getRowCount()==0) 
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
        }
    }//GEN-LAST:event_suaActionPerformed

    private void timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemActionPerformed
       
        // TODO add your handling code here:
        String ten = timten.getText().trim();
        DefaultTableModel dtm = (DefaultTableModel)tbl.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        tbl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ten));
       
    }//GEN-LAST:event_timKiemActionPerformed

    private void cl_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_btActionPerformed
        // TODO add your handling code here:
        ma.setText("");
        tenSach.setText("");
        loai.setSelectedIndex(0);
        tacgia.setText("");
        nxb.setText("");
        ncc.setText("");
        bia.setText("");
        sl.setText("");
        namxb.setText("");
        gia.setText("");
        timten.setText("");
        anh.setText("");
        ma.requestFocus();
        tbl.setRowSorter(null);
    }//GEN-LAST:event_cl_btActionPerformed

    private void tbl_loaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_loaiMouseClicked
        // TODO add your handling code here:
        int row = this.tbl_loai.getSelectedRow();
        this.maloai.setText((String)(tbl_loai.getValueAt(row, 0)));
        this.maloai.setEditable(false);
        this.tenloai.setText((String)(tbl_loai.getValueAt(row, 1)));
        
    }//GEN-LAST:event_tbl_loaiMouseClicked

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
         // button thêm loại
        maloai.setText("");
        kimloai.setText("");
        tenloai.setText("");
        tenloai.requestFocus();
        tbl_loai.setRowSorter(null);
    }//GEN-LAST:event_themActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //Luu loai sach
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            String ten = tenloai.getText().trim();
            String sql="insert into loaiSach\n" +
            "values ( N'"+ten+"')";
            int kq=loaiSachdao.ThemXoaSua(sql);
            if(kq!=-1)
            {
                loaiS = loaiSachdao.layLoaiSach();
                laydulieuLS(loaiS);
                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã NV này đã tồn tại, không thể thêm", "Thông báo", 2);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void xoaloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaloaiActionPerformed
        // TODO add your handling code here:
        if(tbl_loai.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String ma = maloai.getText().trim();
                String sql = "delete from loaiSach where maLoai = '"+ma+"'";
                if(loaiSachdao.ThemXoaSua(sql)!=-1)
                {
                    loaiS = loaiSachdao.layLoaiSach();
                    laydulieuLS(loaiS);
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    
            }
        }else{
            if(tbl_loai.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_xoaloaiActionPerformed

    private void cl_loaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_loaiActionPerformed
        // TODO add your handling code here:
        maloai.setText("");
        kimloai.setText("");
        tenloai.setText("");
        tenloai.requestFocus();
        tbl_loai.setRowSorter(null);
    }//GEN-LAST:event_cl_loaiActionPerformed

    private void sualoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sualoaiActionPerformed
        // TODO add your handling code here:
        if(tbl_loai.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn sửa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String mal = maloai.getText().trim();
                String ten = tenloai.getText().trim();
                String sql =  "update loaiSach set tenLoai = N'"+ten+"'where maLoai = '"+mal+"'";
                loaiSachdao.ThemXoaSua(sql);
                loaiS = loaiSachdao.layLoaiSach();
                laydulieuLS(loaiS);
                JOptionPane.showMessageDialog(this, "Sửa thành công !", "Thông báo", 1);
            }
        }else{
            if(tbl_loai.getRowCount()==0) 
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần sửa","Thông báo",2);
        }
    }//GEN-LAST:event_sualoaiActionPerformed

    private void luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            String maS = ma.getText().trim();
            String tenS = tenSach.getText().trim();
            String loaiS = loai.getSelectedItem().toString();
            String tacG = tacgia.getText().trim();
            String nhaxb = nxb.getText().trim();
            String nhacc = ncc.getText().trim();
            String loaiB = bia.getText().trim();
            String hA = anh.getText().trim();
            String soL = sl.getText().trim();
            String namXb= namxb.getText().trim();
            String G=gia.getText().trim();
            
            String sql="insert into Sach\n" +
                    " values(N'"+tenS+"',LEFT('"+loaiS+"',1),N'"+tacG+"',N'"+nhaxb+"',N'"+nhacc+"',N'"+loaiB+"','"+hA+"','"+soL+"','"+namXb+"','"+G+"')";
            int kq=sachdao.ThemXoaSua(sql);
            if(kq!=-1)
            {
                dsS = sachdao.layDanhSachS();
                laydulieuS(dsS);
                JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông báo",1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã NV này đã tồn tại, không thể thêm", "Thông báo", 2);
        }
    }//GEN-LAST:event_luuActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        if(tbl.getSelectedRowCount()==1)
        {
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                String maS = ma.getText().trim();
                
                String sql = "delete from Sach where maSach = '"+maS+"'";
                if(sachdao.ThemXoaSua(sql)!=-1)
                {
                    dsS = sachdao.layDanhSachS();
                    laydulieuS(dsS);
                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông báo", 1);
                }
                else
                    JOptionPane.showMessageDialog(this, "Dữ liệu này đang được sử dụng, không thể xóa", "Thông báo", 2);
                    
            }
        }else{
            if(tbl.getRowCount()==0)
                JOptionPane.showMessageDialog(this, "Bảng trống","Thông báo",2);
            else
                JOptionPane.showMessageDialog(this, "Chưa chọn dòng cần xóa","Thông báo",2);
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //timkiem
        String ten = kimloai.getText().trim();
        DefaultTableModel dtm = (DefaultTableModel)tbl_loai.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        tbl_loai.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ten));
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anh;
    private javax.swing.JLabel as;
    private javax.swing.JTextField bia;
    private javax.swing.JButton cl_bt;
    private javax.swing.JButton cl_loai;
    private javax.swing.JScrollPane d;
    private javax.swing.JScrollPane f;
    private javax.swing.JTextField gia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField kimloai;
    private javax.swing.JComboBox loai;
    private javax.swing.JButton luu;
    private javax.swing.JTextField ma;
    private javax.swing.JTextField maloai;
    private javax.swing.JTextField namxb;
    private javax.swing.JTextField ncc;
    private javax.swing.JTextField nxb;
    private javax.swing.JTextField sl;
    private javax.swing.JButton sua;
    private javax.swing.JButton sualoai;
    private javax.swing.JTextField tacgia;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tbl_loai;
    private javax.swing.JTextField tenSach;
    private javax.swing.JTextField tenloai;
    private javax.swing.JButton them;
    private javax.swing.JButton timKiem;
    private javax.swing.JTextField timten;
    private javax.swing.JButton xoa;
    private javax.swing.JButton xoaloai;
    // End of variables declaration//GEN-END:variables

    

    
}
